### ISSUE TITLE
Support for Null-Safety 

### ISSUE THREAD

**Issue by sameeerkashyap** [Jaguar-dart/observable_ish#3]
Hello!, I wanted to know if there is any plans for null-safety as the package I'm trying to migrate depends on this. 
If there's any help required I'm willing to make a PR for the same!

**Comment by tejainece** [comment]
Please feel free to make a PR.

My intention was to add null safety support after the feature us fully integrated into the Dart toolchain.

**Comment by sameeerkashyap** [comment]
@tejainece  Should be up in a day or two

**Comment by IchordeDionysos** [comment]
@tejainece @Sameerkash would appreciate if the package would support null safety 👍 

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

This is due to some features on pub.dev that mark packages as preview releases until the underlying Dart/Flutter version is released to stable.

**Comment by sameeerkashyap** [comment]
> @tejainece @Sameerkash would appreciate if the package would support null safety 👍 
> 
> The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).
> 
> This is due to some features on pub.dev that mark packages as preview releases until the underlying Dart/Flutter version is released to stable.



I am almost done with it, but I wasn't able to pass all test cases and it wasn't the best migration. 

So I have to sit down and go line by line, which I haven't found the time for since I have my exams going on. 

So it'll be over this week and I'll be able to work on this next week. 

But in the mean time if someone can do it. That works too.

**Comment by rcsousa14** [comment]
Any updates on null safety?

**Comment by sameeerkashyap** [comment]
> Any updates on null safety? 

I've migrated it. 
Waiting for @tejainece to merge and publish it.

**Comment by tejainece** [comment]
I will review it and publish it in a day or two.

**Comment by sameeerkashyap** [comment]
@tejainece any updates?

**Comment by yakupbaser** [comment]
@tejainece we wait your null safety update.

**Comment by tejainece** [comment]
Working on it. I will publish today or tomorrow. Sorry for delay.

**Comment by yakupbaser** [comment]
thanks in advence

**Comment by a43501** [comment]
> Working on it. I will publish today or tomorrow. Sorry for delay.

@tejainece thank you

**Comment by yakupbaser** [comment]
come on man! Thats a good day for it :)

**Comment by tejainece** [comment]
Have you guys tested it? ok with the breaking changes? Then, I can publish today.

**Comment by tejainece** [comment]
Version 3.0.0 with null safety support has published to pub.dev. Please check it out and let me know if you find any problems.
