### ISSUE TITLE
Don't update the value 

### ISSUE THREAD

**Issue by enri90** [Jaguar-dart/observable_ish#6]
I don't understand why in this version it doesn't update
stacked: ^2.0.2
stacked_services: ^0.8.1
injectable: ^1.2.2
observable_ish: ^3.0.0

`
   RxValue<String?> _fullname = RxValue<String?>(null);
.....
  _fullname.value = 'test';   <--- work after
   User user = await _firestoreService.getUser(uid);
  _fullname.value = user.name;   <--- not work 

`

I don't update the value after await
someone has the same problem as me in the null-safety version?

**Comment by tejainece** [comment]
@enri90 I will try to reproduce and fix it. A simple isolated example reproducing this error bug will be very helpful.

**Comment by tejainece** [comment]
@enri90 the following code works fine:

```dart
import 'package:observable_ish/observable_ish.dart';

main() {
  final rxInts = RxValue<int>(5);
  print(rxInts.value); // => 5
  rxInts.value = 10;
  rxInts.value = 15;
  rxInts.values.listen((int v) => print(v)); // => 15, 20, 25
  rxInts.value = 20;
  rxInts.value = 25;
}
```

produces expected result:

```
5
15
20
25
```

**Comment by tejainece** [comment]
Please reopen the issue if you still have the problem.
